In [3]:
import numpy as np

# numpy的性能优势对比
# python原生实现
def sum(n:int):
    a = [i**2 for i in range(n)]
    b = [i**2 for i in range(n)]
    c = []
    for i,j in zip(a,b):
        c.append(i+j)
    return c


# numpy 实现
def sum_np(n:int):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 2
    return a + b


In [11]:
%timeit sum(1000)

131 μs ± 2.29 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
%timeit sum_np(1000)

3.79 μs ± 36.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
# 通过python原生的list来创建
l1 = [ 1, 2, 3, 4 ]
l2 = [
    [ 2, 3, 4, 5 ],
    [ 3, 4, 5, 6]
]

arr1 = np.array(l1)
arr2 = np.array(l2)


In [20]:
arr1

array([1, 2, 3, 4])

In [21]:
arr2

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])


调用array的属性


In [32]:
# 调用array的属性
arr1.shape

(4,)

In [25]:
arr2.shape

(2, 4)

In [26]:
arr1.ndim

1

In [27]:
arr2.ndim

2

In [28]:
arr1.size

4

In [29]:
arr2.size

8

In [30]:
arr1.dtype

dtype('int64')

In [31]:
arr2.dtype

dtype('int64')

In [36]:
# 查看arange函数
# 推荐使用第一种，第二种占下方显示的空间...
np.arange?
help(np.arange)
# arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warn

In [37]:
# 获取一维向量
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [39]:
np.ones?
# np.ones(shape, dtype=None, order='C', *, device=None, like=None)
# shape: 提供一个数字n，返回n个1的一维向量。提供一个二元组(2,3),返回2行3列的1

In [40]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ones( (2,3) )

array([[1., 1., 1.],
       [1., 1., 1.]])

In [1]:
np.ones_like?
# np.ones_like(
#     a,         这个是模板
#     dtype=None,
#     order='K',
#     subok=True,
#     shape=None,
#     *,
#     device=None,
# )

Object `np.ones_like` not found.


In [17]:
x1 = [1,3,4,5,6]
x2 = [
    [1, 2, 3, 4, 5],
    [3, 4, 5, 6, 7]
]

In [45]:
np.ones_like(x1)

array([1, 1, 1, 1, 1])

In [46]:
np.ones_like(x2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [3]:
# 和ones/ones_like相同
np.zeros_like?

In [49]:
np.zeros_like(x1)

array([0, 0, 0, 0, 0])

In [50]:
np.zeros_like(x2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [51]:
np.empty?
# empty(shape, dtype=float, order='C', *, device=None, like=None)
# 里面元素是随机的

In [52]:
np.empty(4)

array([0.00000000e+000, 1.10746561e-311, 1.10746561e-311, 1.10746561e-311])

In [53]:
np.empty(4,dtype=int)

array([            0, 2241535356272, 2241535357472, 2241535355232])

In [54]:
np.empty( (2,2) )

array([[2.12199579e-314, 1.10555981e-311],
       [8.55721699e-321, 6.95293141e-310]])

In [55]:
np.empty_like?
# empty_like(prototype, dtype=None, order='K', subok=True, shape=None, *,
#           device=None)
# prototype: 根据传入的对象，返回同类型但元素随机的array

In [56]:
np.empty_like(x1)

array([25895968444448860, 23925768161198147, 32370111954616435,
           2241535344640,           7077888])

In [57]:
np.empty_like(x2)

array([[-1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [13]:
import sys
sys.version
# 输出的是idea的环境，不是系统变量的原因？
# PyCharm实现的，否则首先使用系统变量

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [2]:
import numpy as np

# np.full(
#     shape,
#     fill_value,
#     dtype=None,
#     order='C',
#     *,
#     device=None,
#     like=None,
# )
np.full?

In [22]:
np.full(4,1)

array([1, 1, 1, 1])

In [23]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [24]:
np.full_like(x1,666)

array([666, 666, 666, 666, 666])

In [25]:
np.full_like(x2, 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [28]:
np.random.randn?
# randn(d0, d1, ..., dn)
# 返回维度为d0*d1*...*dn的数组，且符合正态分布

In [29]:
np.random.randn()

1.0015358274407484

In [30]:
np.random.randn(3)

array([ 0.31482864, -0.73433727,  0.09028981])

In [31]:
np.random.randn(3,2)

array([[ 1.12230245,  1.13655325],
       [ 1.10020571, -0.16900517],
       [-0.18112429, -0.57835511]])

In [32]:
np.random.randn(3,4,6)

array([[[-2.00244356e-01,  9.16078369e-01,  8.48348664e-01,
         -1.30839252e+00,  1.15651388e+00, -6.04746454e-01],
        [-4.90237136e-01,  2.18280641e-01,  2.79386569e-01,
          1.29338381e+00,  2.29056111e+00,  1.72864044e-01],
        [-1.84337447e-01,  1.57629452e-01,  1.51667254e+00,
         -1.59108316e+00,  1.54964946e+00,  8.92723989e-02],
        [ 1.23211938e+00,  1.60085229e+00, -8.78390229e-01,
         -4.21877923e-01,  1.79446286e+00, -1.15569578e+00]],

       [[ 7.73033760e-01,  2.23484800e-01,  8.30580867e-02,
          7.91759615e-01,  5.03247098e-01, -2.34566226e-01],
        [-1.44416845e+00,  3.62387829e-01,  1.96886578e+00,
         -9.41249120e-01, -1.49406740e+00,  1.49456684e+00],
        [-1.39797526e+00, -8.20605794e-01,  2.58491662e-01,
          5.17397515e-01, -4.03850381e-01,  6.22298464e-01],
        [-1.05592349e+00,  1.82362466e+00, -1.63776456e+00,
          1.58820284e+00, -1.26396847e+00,  7.14606720e-01]],

       [[ 9.88892587e-02, -3

In [36]:
# array本身支持大量的操作和函数
arr = np.arange(10).reshape(2,5) 
# 需要注意reshape的参数的乘积必须等于原数组的个数
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
arr.shape

(2, 5)

In [43]:
arr+1 
# 所有元素+1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
arr*10
# 所有元素*10

array([[ 0, 10, 20, 30, 40],
       [50, 60, 70, 80, 90]])

In [40]:
np.sin(arr)
# 求sin

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [46]:
np.exp(arr)
# 求e的x次方，x为数组的元素

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [53]:
arr1 = np.array([
    [1,2,3],
    [2,2,3]
])
arr2 = np.array([
    [1,2,3],
    [2,2,3]
])
# 对相同维度的数组进行 算数 运算

In [54]:
arr1+arr2

array([[2, 4, 6],
       [4, 4, 6]])

In [55]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [56]:
arr1*arr2

array([[1, 4, 9],
       [4, 4, 9]])

In [57]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

  对数组使用索引查询

In [9]:
import numpy as np
x1 = np.arange(10) ** 2
x2 = np.arange(9).reshape(3,3)

In [10]:
print(x1,'\n',x2)

[ 0  1  4  9 16 25 36 49 64 81] 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 一维数组类似于Python的List
x1[3]

np.int64(9)

In [13]:
x1[:4]

array([0, 1, 4, 9])

In [16]:
x1[2:-1]

array([ 4,  9, 16, 25, 36, 49, 64])

In [17]:
x1[:-4]

array([ 0,  1,  4,  9, 16, 25])

In [19]:
# 二维数组,不使用多个[][]来分别选行和列，使用一个[row,col]来选择
x2[2]

array([6, 7, 8])

In [21]:
x2[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
x2[:,2]

array([2, 5, 8])

In [23]:
x2[:, 0:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

In [25]:
x2[1,1]

np.int64(4)

In [26]:
# Numpy切片的修改可以影响原数组
x2[1] = 3
x2

array([[0, 1, 2],
       [3, 3, 3],
       [6, 7, 8]])

In [33]:
x3 = [1,2,3,4,5]
x3[:3] = [1,3,4]
x3

[1, 3, 4, 4, 5]

In [63]:
# 神奇索引：即给定索引时可以提供不连续的索引
# 且返回的数组是按给定索引的顺序给出的

# 一维数组
print(x1)
x1[ [0,2,1] ]

[ 0  1  4  9 16 25 36 49 64 81]


array([0, 4, 1])

In [64]:
# 根据index的形状，将index的元素作为一维数组下标，然后根据下标指向的值填充到index中
index = [
    [0,1],
    [1,2]
]
x1[index]

array([[0, 1],
       [1, 4]])

In [61]:
# 二维数组
x2[ [0,2] ]

array([[0, 1, 2],
       [6, 7, 8]])

In [35]:
# 列
x2[:, [0,2,1]]

array([[0, 2, 1],
       [3, 3, 3],
       [6, 8, 7]])

In [38]:
# 单个元素,[x1,x2,...,xn],[y1,y2,...,yn]，获取[x1][y1],[x2][y2]的元素,必须保证x和y的数量相同

x2[[0,1],[0,1]]

array([0, 3])

In [42]:
x2[0:1,0:2]

array([[0, 1]])

In [51]:
# 如果indexs是Python的列表，传入一个参数为列表时，则在indexs的基础上，将各个元素替换为x2所对应的行即可
indexs = [
    [1,0],
    [2,1]
]
print(x2)
x2[indexs]

[[0 1 2]
 [3 3 3]
 [6 7 8]]


array([[[3, 3, 3],
        [0, 1, 2]],

       [[6, 7, 8],
        [3, 3, 3]]])

In [53]:
# 传入两个index列表，则根据index的形状，将两个index的对应位置的元素x1,y1取出，找到原数组x1,y1的元素填充index的位置即可
i1 = [
    [0,1],
    [0,2]
]
i2 = [
    [1,1],
    [2,2]
]
print(x2)
x2[i1,i2]

[[0 1 2]
 [3 3 3]
 [6 7 8]]


array([[1, 3],
       [2, 8]])

In [57]:
print(x2)
index = np.array([[0,1],[0,2]])
x2[index]

[[0 1 2]
 [3 3 3]
 [6 7 8]]


array([[[0, 1, 2],
        [3, 3, 3]],

       [[0, 1, 2],
        [6, 7, 8]]])

In [60]:
x = np.arange(10)
index = np.array([[1,2],[1,3]])
x[index]

array([[1, 2],
       [1, 3]])

In [1]:
import numpy as np

# 生成10个1-100之间的随机数
arr = np.random.randint(1,100,10)
print("随机数组：",arr)
# 参数axis用于多维数组，指定轴排序,一维数组默认为-1
indexs = arr.argsort(axis=-1) # 参数axis用于多维数组，指定轴排序
print("排序坐标：", indexs)
print("根据坐标打印的数组元素：",end="")
for i in indexs:
    print(arr[i],end=" ")
print()
# 获取下标数组的后三个元素
prev_index = indexs[-3:]
print("最大的前3个元素的下标为",prev_index)
prev_index = prev_index[::-1]
print("（按元素大小排序）最大的前3个元素的下标为",prev_index)
print("最大的前3个数为: ",end="")
for i in prev_index:
    print(arr[i],end=" ")

随机数组： [58 32 83 47 68 31 95 86 86 35]
排序坐标： [5 1 9 3 0 4 2 7 8 6]
根据坐标打印的数组元素：31 32 35 47 58 68 83 86 86 95 
最大的前3个元素的下标为 [7 8 6]
（按元素大小排序）最大的前3个元素的下标为 [6 8 7]
最大的前3个数为: 95 86 86 

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [6]:
x[ x>5 ]

array([6, 7, 8, 9])

In [15]:
x = np.arange(10)
x[ x%2==1 ] = 0
x

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

In [18]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [20]:
x>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [21]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
# 获取第三列大于5的行的布尔索引
x[:,3] > 5

array([False,  True,  True,  True])

In [23]:
x[ x[:,3] > 5 ]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

random的随机函数

In [38]:
import numpy as np
np.random.seed(666) # 当种子设定后，所有人的随机数都相同

1 rand(d0,...,dn)

In [39]:
np.random.rand(5)

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796])

In [40]:
np.random.rand(3,4)

array([[0.0127032 , 0.4135877 , 0.04881279, 0.09992856],
       [0.50806631, 0.20024754, 0.74415417, 0.192892  ],
       [0.70084475, 0.29322811, 0.77447945, 0.00510884]])

2 randn(d0,...,dn)

In [41]:
np.random.randn(5)

array([-0.88192175,  1.25327039,  0.02801672,  0.40855719,  0.53928565])

In [43]:
np.random.randn(3,4)

array([[-1.54984701,  0.72946452, -0.32695477,  1.14133677],
       [ 0.45243662, -2.23496877,  1.27047766, -0.72928821],
       [ 1.35925255, -1.20990266, -0.04618272, -0.44118244]])

3 randint( low, [high, size, dtype] )
生成的数在[low,high)之间，不指定high则生成[0,low)之间的数

In [44]:
np.random.randint(6)

4

In [46]:
np.random.randint(1,10)

9

In [49]:
np.random.randint(10,30,size=5) #size为一维时，可不使用元组表示

array([14, 22, 28, 15, 26], dtype=int32)

In [50]:
np.random.randint(10,30,size=(5,2))

array([[14, 24],
       [23, 27],
       [17, 20],
       [22, 25],
       [20, 11]], dtype=int32)

4 random([size])

In [51]:
np.random.random()

0.6509180757030384

In [52]:
np.random.random(5)

array([0.51832728, 0.00355049, 0.80309176, 0.35932938, 0.42014544])

In [53]:
np.random.random((5,2))

array([[0.2026436 , 0.63279787],
       [0.18935861, 0.1308497 ],
       [0.75765845, 0.34158167],
       [0.52138487, 0.88302327],
       [0.44914216, 0.23902229]])

5 choice( a [, size, replace, p] )
根据a来生成随机数

In [54]:
# a是数字，则从range(a)中选择
np.random.choice(5,3) 

array([2, 0, 1], dtype=int32)

In [56]:
np.random.choice(5,(5,2))

array([[0, 0],
       [1, 2],
       [1, 1],
       [2, 2],
       [4, 2]], dtype=int32)

In [57]:
l = [1,2,3,3,3,2,2,1]
np.random.choice(l,5)

array([1, 2, 2, 2, 3])

6 shuffle(x) 将x随机排列

In [64]:
l = [1,2,3,4,5,6,7,8]
np.random.shuffle(l)
l

[1, 6, 5, 3, 4, 2, 8, 7]

In [65]:
l = [
    [ 1, 1, 1, 1 ],
    [ 2, 2, 2, 2 ],
    [ 3, 3, 3, 3 ]
]
# 随机打乱行
np.random.shuffle(l)
l

[[3, 3, 3, 3], [2, 2, 2, 2], [1, 1, 1, 1]]

7 permutation(x)
将x进行随机排列

In [66]:
np.random.permutation(10)

array([5, 6, 7, 4, 8, 1, 9, 2, 3, 0], dtype=int32)

In [69]:
l = np.arange(9).reshape( (3,3) )
l

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
np.random.permutation( l )

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [71]:
# 该函数会返回一个打乱的数组，不同于shuffle是打乱本身的数组
l

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8 normal( [loc, scale, size] )
根据平均值loc和方差scale生成高斯分布的数字

In [72]:
np.random.normal(1,10,10)

array([  5.69534314,   7.36420302, -17.50816505,  15.06375318,
        -0.67932238,   6.1004571 ,   5.27013988, -10.17608559,
        12.59436829,  -0.37953426])

In [73]:
np.random.normal(1,100,(3,3))

array([[ 66.04299113,   5.23292326, 165.80307244],
       [ -4.65942325, 132.36560676,  51.32695446],
       [-54.14191749,  43.76385552, -71.26713845]])

9 uniform( [low, high, size] )
在[low,high)之间生成均匀分布的数字

In [74]:
np.random.uniform( 1, 10, 10 )

array([4.4470818 , 7.33697676, 8.45805318, 6.23391206, 4.48243537,
       4.56832367, 2.35352783, 1.79517381, 8.20018579, 8.80840212])

In [75]:
np.random.uniform( 1, 10, (3,3) )

array([[8.97889452, 7.86251152, 2.94288491],
       [6.42805317, 2.59195944, 2.41837233],
       [4.8709058 , 2.22199194, 2.8383966 ]])

Numpy的数学统计函数

In [76]:
import numpy as np

arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
# 不指定axis，默认将二维数组当作一维数组进行计算
np.sum(arr)

np.int64(66)

In [78]:
np.prod(arr)

np.int64(0)

In [79]:
# 求前n的累加和
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66])

In [80]:
np.cumprod(arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
np.min(arr)

np.int64(0)

In [82]:
np.max(arr)

np.int64(11)

In [84]:
# 获取数组第25%，50%， 75% 的数
np.percentile(arr,[25,50,75])

array([2.75, 5.5 , 8.25])

In [85]:
# 与percentile 不同的是使用小数
np.quantile(arr, [0.25, 0.5, 0.75])

array([2.75, 5.5 , 8.25])

In [86]:
np.median(arr)

np.float64(5.5)

In [87]:
np.mean(arr)

np.float64(5.5)

In [88]:
np.std(arr)

np.float64(3.452052529534663)

In [89]:
np.var(arr)

np.float64(11.916666666666666)

In [91]:
weights = np.random.rand(*arr.shape)

array([[0.07222205, 0.10544706, 0.64744317, 0.74614719],
       [0.29378666, 0.01920958, 0.07128293, 0.60811273],
       [0.14110248, 0.03073621, 0.96667746, 0.96337559]])

In [94]:
np.average(arr, weights=weights)

np.float64(6.701000771632676)

In [93]:
# 使用*进行解包
print(arr.shape)
print(*arr.shape)

(3, 4)
3 4


针对axis参数

In [95]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
arr.sum?

Docstring:
a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

Return the sum of the array elements over the given axis.

Refer to `numpy.sum` for full documentation.

See Also
--------
numpy.sum : equivalent function
Type:      builtin_function_or_method

In [98]:
# 即指定x，获取列的求和, 如果忘了，用一个行列不同的数组，根据结果判断一下就行
# 也可以理解为一把梳子，从将所有行，向下刷成一行
arr.sum(axis=0)

array([12, 15, 18, 21])

In [99]:
arr.sum(axis=1)

array([ 6, 22, 38])

In [100]:
arr.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [101]:
arr.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

案例：机器学习中将数据进行标准化

In [116]:
# numpy的广播 arr1-arr2,两个数组的列数相同，arr1的每行的对应列都减去arr2
import numpy as np
arr1 = np.arange(12).reshape((3,4))
print(arr1)
arr2 = [1,1,1,1]
arr1 - arr2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [103]:
import numpy as np

arr = np.arange(12).reshape( (3,4) )
arr
# 对于二维数组的理解：一行是一个实体，每个列是该实体的属性
# 数据标准化：
#     1、对于机器学习和神经网络来说，不同列的量纲应该相同，训练收敛的更快
#     2、商品的价格和销售的数字相差太大,不具备可比性，一般将其进行标准化
#     3、不同列代表不同的特征，所以axis=0
#     4、标准化一般使用 A = ( A-mean(A,axis=0) ) /  std(A,axis=0) 进行

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
# 计算每列的均值
mean = arr.mean(axis=0)
print(mean)
mean = np.mean(arr,axis=0)
print(mean)

[4. 5. 6. 7.]
[4. 5. 6. 7.]


In [111]:
# 计算每列的标准差
std = arr.std(axis=0)
std

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [120]:
ret = ( arr - mean ) / std
ret
# 有0是因为就3列，且中间列的元素是平均数

array([[-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487,  1.22474487]])

In [122]:
# 使用随机数的案例
arr = np.random.randint(1, 100, size=(3,4) )
arr

array([[66, 12, 58, 76],
       [31, 41, 92, 91],
       [10, 20, 85, 35]], dtype=int32)

In [124]:
ret = ( arr - arr.mean(axis=0) ) / arr.std(axis=0)
ret

array([[ 1.31319831, -1.00850764, -1.38708029,  0.36616087],
       [-0.20203051,  1.36284817,  0.93229987,  0.99990083],
       [-1.1111678 , -0.35434052,  0.45478042, -1.36606169]])

数据合并

In [2]:
import numpy as np

# 列相同
arr1 = np.arange(6).reshape(2,3)
arr2 = np.random.randint(1,100,(4,3))
np.concatenate([arr1,arr2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [49, 64, 71],
       [19, 16, 89],
       [38, 77, 75],
       [45,  1, 88]])

In [3]:
np.vstack([arr1,arr2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [49, 64, 71],
       [19, 16, 89],
       [38, 77, 75],
       [45,  1, 88]])

In [8]:
# 行相同
arr1 = np.arange(12).reshape(3,4)
arr2 = np.random.randint(1,20,(3,2))

array([[ 3, 12],
       [13, 10],
       [14,  9]], dtype=int32)

In [9]:
np.concat([arr1,arr2],axis=1)

array([[ 0,  1,  2,  3,  3, 12],
       [ 4,  5,  6,  7, 13, 10],
       [ 8,  9, 10, 11, 14,  9]])

In [11]:
np.hstack([arr1,arr2])

array([[ 0,  1,  2,  3,  3, 12],
       [ 4,  5,  6,  7, 13, 10],
       [ 8,  9, 10, 11, 14,  9]])