In [3]:
from webbrowser import open_new

import numpy as np

# numpy的性能优势对比
# python原生实现
def sum(n:int):
    a = [i**2 for i in range(n)]
    b = [i**2 for i in range(n)]
    c = []
    for i,j in zip(a,b):
        c.append(i+j)
    return c

# numpy 实现
def sum_np(n:int):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 2
    return a + b


In [11]:
%timeit sum(1000)

131 μs ± 2.29 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [13]:
%timeit sum_np(1000)

3.79 μs ± 36.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
# 通过python原生的list来创建
l1 = [ 1, 2, 3, 4 ]
l2 = [
    [ 2, 3, 4, 5 ],
    [ 3, 4, 5, 6]
]

arr1 = np.array(l1)
arr2 = np.array(l2)


In [20]:
arr1

array([1, 2, 3, 4])

In [21]:
arr2

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])


调用array的属性


In [32]:
# 调用array的属性
arr1.shape

(4,)

In [25]:
arr2.shape

(2, 4)

In [26]:
arr1.ndim

1

In [27]:
arr2.ndim

2

In [28]:
arr1.size

4

In [29]:
arr2.size

8

In [30]:
arr1.dtype

dtype('int64')

In [31]:
arr2.dtype

dtype('int64')

In [36]:
# 查看arange函数
# 推荐使用第一种，第二种占空间...
np.arange?
help(np.arange)
# arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warn

In [37]:
# 获取一维向量
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [39]:
np.ones?
# np.ones(shape, dtype=None, order='C', *, device=None, like=None)
# shape: 提供一个数字n，返回n个1的一维向量。提供一个二元组(2,3),返回2行3列的1

In [40]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ones( (2,3) )

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.ones_like?
# np.ones_like(
#     a,         这个是模板
#     dtype=None,
#     order='K',
#     subok=True,
#     shape=None,
#     *,
#     device=None,
# )

In [43]:
x1 = [1,3,4,5,6]
x2 = [
    [1, 2, 3, 4, 5],
    [3, 4, 5, 6, 7]
]

In [45]:
np.ones_like(x1)

array([1, 1, 1, 1, 1])

In [46]:
np.ones_like(x2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [47]:
# 和ones/ones_like相同
np.zeros_like?

In [49]:
np.zeros_like(x1)

array([0, 0, 0, 0, 0])

In [50]:
np.zeros_like(x2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [51]:
np.empty?
# empty(shape, dtype=float, order='C', *, device=None, like=None)
# 里面元素是随机的

In [52]:
np.empty(4)

array([0.00000000e+000, 1.10746561e-311, 1.10746561e-311, 1.10746561e-311])

In [53]:
np.empty(4,dtype=int)

array([            0, 2241535356272, 2241535357472, 2241535355232])

In [54]:
np.empty( (2,2) )

array([[2.12199579e-314, 1.10555981e-311],
       [8.55721699e-321, 6.95293141e-310]])

In [55]:
np.empty_like?
# empty_like(prototype, dtype=None, order='K', subok=True, shape=None, *,
#           device=None)
# prototype: 根据传入的对象，返回同类型但元素随机的array

In [56]:
np.empty_like(x1)

array([25895968444448860, 23925768161198147, 32370111954616435,
           2241535344640,           7077888])

In [57]:
np.empty_like(x2)

array([[-1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])